### ISSUE TITLE
Bug to don't let login in chat because of cache?

### ISSUE THREAD

**Issue by martinlacorrona** [Arquisoft/dechat_es1b#108]

**Comment by martinlacorrona** [comment]
If I clear cache in Google Chrome, this error dissappear, but we have any tool to manage clear cache in every session?

**Comment by srensamblador** [comment]
This is a double edged sword, because if we clear the cache on reload, each time a user reloads he would have to login again.

if we think about the final users we just need to ensure a fresh account can login and that the session is properly ended when the user clicks the disconnect button.

Our own pods during developing might not be representative of what the users actually encounter

**Comment by martinlacorrona** [comment]
@JavierUrones  add this in considerations https://github.com/Arquisoft/dechat_es1b/wiki/Considerations
