### ISSUE TITLE
Contact list

### ISSUE THREAD

**Issue by srensamblador** [Arquisoft/dechat_es1b#13]
We need to display the friends list of the user so he can interact with them later on.
For now, we are in a very early stage therefore we will focus on making it work rather than making it pretty.

**Comment by LuisBoto** [comment]
Seems like the idflex library already retrieves a friends list. Does it not work properly? I have been unable to actually add a contact on my POD so i couldn't test if any information was being retrieved at all from the pod

**Comment by srensamblador** [comment]
Yes, indeed. Right now we can already retrieve each friends' WebID with ldflex. There's still a few things left.
* It would be nice to get a formatted version of the friend's name in order to display it to the user in the contact list
* We will need to be able to access a friend's inbox once we start doing the chat itself
* There's still all the presentation side of the friend list yet to be done. We need to think (and implement) how to display this information to the user so he can start chatting with one.

I have an idea for the first point. The rest is still pending, if anyone wants to explore it, that would be great.

**Comment by LuisBoto** [comment]
We can probably retrieve the friend and user's inboxes no problem as long as we have their WebId's. However i am unsure how can we get the friend's WebId since we've got no session object corresponding to them?

As for the friend list, i think we could make the friend list clickable and send the user to a new screen, where the message input field and chat would be.

**Comment by LuisBoto** [comment]
Closing until further modification is needed
