### ISSUE TITLE
Developement of a basic pod writer

### ISSUE THREAD

**Issue by uo257493** [Arquisoft/dechat_es1b#37]
As we are going to do with the reader we should do the same with a writer.
A kind of test to write in a simple html a text to be uploaded to a POD

**Comment by LuisBoto** [comment]
I just pushed some code rn to the features/chat-options branch since it uses the textAreas @JavierUrones made. It basically takes the message and writes it to a new file within the contact's POD. However no info about who sent the message is attached, and each new message is sent in a new file. 

It's really dirty for now, but main functionality is there. Let me know what you think.

**Comment by LuisBoto** [comment]
Closing since for now we are just lacking the pod-reader
